// Copyright (c) bstadick and contributors. MIT License - see LICENSE file

using CommunityToolkit.Maui;

namespace MauiNUnitRunner.Controls;

/// <summary>
/// Extensions for MauiAppBuilder
/// </summary>
public static class AppBuilderExtensions
{
    /// <summary>
    /// Initializes the .NET MAUI NUnit Runner Controls Library
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
    /// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="MauiNUnitRunner.Controls"/></returns>
    public static MauiAppBuilder UseMauiNUnitRunner(this MauiAppBuilder builder)
    {
        // Initialize the MAUI Community Toolkit to use for the FileSaver component
        return builder.UseMauiCommunityToolkit();
    }
}