name: .NET Push

on: [workflow_dispatch]

env:
  CONFIGURATION: Release
  GLOBALJSON: .\src\global.json
  PROJECTDIRPATH: .\src\MauiNUnitRunner.Controls
  EXAMPLEPROJECTDIRPATH: .\src\MauiNUnitRunner.Examples\Runner\bin\Release\net8.0-ios\ios-arm64
  SOLUTION: .\src\MauiNUnitRunner.sln
  PROJECT: .\src\MauiNUnitRunner.Controls\MauiNUnitRunner.Controls.csproj

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        global-json-file: ${{ env.GLOBALJSON }}
    - name: Restore with dotnet
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 3
        retry_on: error
        command: dotnet restore "${{ env.SOLUTION }}"
    - name: Build with dotnet
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 3
        retry_on: error
        command: dotnet build "${{ env.SOLUTION }}" -c ${{ env.CONFIGURATION }} --no-restore
    - name: Pack with dotnet
      run: dotnet pack "${{ env.PROJECT }}" -c ${{ env.CONFIGURATION }} --no-build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-artifacts
        path: |
          ${{ env.PROJECTDIRPATH }}\bin\${{ env.CONFIGURATION }}\*.nupkg
          ${{ env.EXAMPLEPROJECTDIRPATH }}\bin\${{ env.CONFIGURATION }}\*-ios\ios-arm64\*.ipa
