name: .NET Push

on: [push, workflow_dispatch]

env:
  CONFIGURATION: Release
  GLOBALJSON: .\src\global.json
  PROJECTPATH: .\src\MauiNUnitRunner.Controls
  TESTPROJECTPATH: .\src\MauiNUnitRunner.Controls.Tests
  SOLUTION: .\src\MauiNUnitRunner.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        global-json-file: ${{ env.GLOBALJSON }}
    - name: Build with dotnet
      run: dotnet build "${{ env.SOLUTION }}" -c ${{ env.CONFIGURATION }}
    - name: Build examples with dotnet
      run: dotnet build "${{ env.SOLUTION }}" -c Example
    - name: Build iOS simulator examples with dotnet
      run: dotnet build "${{ env.SOLUTION }}" -c Example -p:Platform=iPhoneSimulator
    - name: Test with dotnet
      run: dotnet test "${{ env.SOLUTION }}" -c UnitTest --logger trx
    - name: Pack with dotnet
      run: dotnet pack "${{ env.SOLUTION }}" -c ${{ env.CONFIGURATION }}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-artifacts
        path: |
          ${{ env.PROJECTPATH }}\bin\${{ env.CONFIGURATION }}\*.nupkg
          ${{ env.TESTPROJECTPATH }}\TestResults\*.trx
